[package]
cairo-version = "2.4.0"
name = "types_test"
version = "0.4.2"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { path = "../../dojo-core" }

[[target.dojo]]
build-external-contracts = []

#[tool.dojo.world]
#name = "types-test"
#description = "Graphql types testing"
# icon_uri = "file://assets/icon.png"
# cover_uri = "file://assets/cover.png"
# website = "https://dojoengine.org"
# socials.x = "https://twitter.com/dojostarknet"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
account_address = "0x295e01fd0ec0e8b5781e0cb0aa9544e4615a3434c95cf1ff4c6b64ca42248ad"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
