[package]
cairo-version = "2.3.1"
name = "dojo_examples"
version = "0.3.10"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { path = "../../crates/dojo-core" }

[[target.dojo]]
build-external-contracts = [  ]

[tool.dojo.world]
description = "example world"
name = "example"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"

# Default account for katana with seed = 0
account_address = "0x295e01fd0ec0e8b5781e0cb0aa9544e4615a3434c95cf1ff4c6b64ca42248ad"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
