[package]
cairo-version = "2.3.1"
description = "The Dojo Core library for autonomous worlds."
name = "dojo"
version = "0.3.6"

[dependencies]
dojo_plugin = { git = "https://github.com/dojoengine/dojo", tag = "v0.3.6" }
starknet = "2.3.1"
